In [2]:
import cv2
import numpy

In [3]:
#Read the image and convert it to grayscale
image = cv2.imread('shape.jpg')
image = cv2.resize(image, None, fx=0.6,fy=0.6)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [4]:
#Now convert the grayscale image to binary image
ret, binary = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)

In [6]:
#Now detect the contours
#retr_external: gives outer lines
#retr_list:complete lines in the image including outside andinsise lines
#retr_tree: shows heirar
contours, hierarchy = cv2.findContours(binary, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_NONE)

In [7]:
#Visualize the data structure
print("Length of contours {}".format(len(contours)))
print("Here is the hierarchy of detected contours :")
print(hierarchy)

Length of contours 7
Here is the hierarchy of detected contours :
[[[-1 -1  1 -1]
  [ 3 -1  2  0]
  [-1 -1 -1  1]
  [ 5  1  4  0]
  [-1 -1 -1  3]
  [-1  3  6  0]
  [-1 -1 -1  5]]]


In [8]:
# draw contours on the original image
image_copy = image.copy()
image_copy = cv2.drawContours(image_copy, contours, -1, (0, 255, 0), thickness=2, lineType=cv2.LINE_AA)

In [ ]:
#Visualizing the results
cv2.imshow('Grayscale Image', gray)
cv2.imshow('Drawn Contours', image_copy)
cv2.imshow('Binary Image', binary)

cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x564f3a6c0ca0) is not the object's thread (0x564f39dccde0).
Cannot move to target thread (0x564f3a6c0ca0)

QObject::moveToThread: Current thread (0x564f3a6c0ca0) is not the object's thread (0x564f39dccde0).
Cannot move to target thread (0x564f3a6c0ca0)

QObject::moveToThread: Current thread (0x564f3a6c0ca0) is not the object's thread (0x564f39dccde0).
Cannot move to target thread (0x564f3a6c0ca0)

QObject::moveToThread: Current thread (0x564f3a6c0ca0) is not the object's thread (0x564f39dccde0).
Cannot move to target thread (0x564f3a6c0ca0)

QObject::moveToThread: Current thread (0x564f3a6c0ca0) is not the object's thread (0x564f39dccde0).
Cannot move to target thread (0x564f3a6c0ca0)

QObject::moveToThread: Current thread (0x564f3a6c0ca0) is not the object's thread (0x564f39dccde0).
Cannot move to target thread (0x564f3a6c0ca0)

QObject::moveToThread: Current thread (0x564f3a6c0ca0) is not the object's thread (0x564f39dccde0).
Cannot move to tar